"""Independent VGen Python SDK for credentials, signatures, and E2EE primitives."""

from .allocation import (
    ALLOCATION_PROOF_CONTEXT,
    ALLOCATION_PROOF_KIND,
    build_allocation_proof_payload,
    verify_allocation_proof,
    worker_certificate_digest,
)
from .authentication import (
    build_service_challenge_request,
    build_service_session_request,
    sign_service_challenge,
)
from .credentials import ServiceCredentials
from .encoding import b64url_decode, b64url_encode, canonical_json
from .envelope import (
    HPKE_ALGORITHM,
    PAYLOAD_ALGORITHM,
    TASK_DATA_KEY_BYTES,
    HpkeCiphertext,
    PayloadCiphertext,
    decrypt_payload,
    encrypt_payload,
    generate_task_data_key,
    generate_workspace_data_key,
    hpke_open,
    hpke_seal,
    task_aad,
    unwrap_task_key,
    unwrap_task_key_for_workspace,
    unwrap_workspace_key,
    workspace_key_aad,
    wrap_task_key,
    wrap_task_key_for_workspace,
    wrap_workspace_key,
)
from .errors import CredentialError, DecryptionError, SignatureError, VGenSdkError
from .http_signatures import (
    RequestSignatureHeaders,
    VerifiedRequestSignature,
    content_digest,
    sign_http_request,
    verify_http_request,
)
from .keys import (
    MANIFEST_CONTEXT,
    SIGNATURE_CONTEXT,
    DeviceKeys,
    deserialize_device_keys,
    device_key_id,
    root_signing_key_id,
    serialize_device_keys,
    sign_message,
    verify_key_manifest,
    verify_message,
)
from .trust import WORKER_OWNER_CERTIFICATE_KIND, verify_worker_owner_certificate

__all__ = [
    "HPKE_ALGORITHM",
    "ALLOCATION_PROOF_CONTEXT",
    "ALLOCATION_PROOF_KIND",
    "MANIFEST_CONTEXT",
    "PAYLOAD_ALGORITHM",
    "SIGNATURE_CONTEXT",
    "TASK_DATA_KEY_BYTES",
    "CredentialError",
    "DecryptionError",
    "DeviceKeys",
    "HpkeCiphertext",
    "PayloadCiphertext",
    "RequestSignatureHeaders",
    "ServiceCredentials",
    "SignatureError",
    "VGenSdkError",
    "VerifiedRequestSignature",
    "WORKER_OWNER_CERTIFICATE_KIND",
    "b64url_decode",
    "b64url_encode",
    "build_service_challenge_request",
    "build_service_session_request",
    "build_allocation_proof_payload",
    "canonical_json",
    "content_digest",
    "decrypt_payload",
    "deserialize_device_keys",
    "device_key_id",
    "encrypt_payload",
    "generate_task_data_key",
    "generate_workspace_data_key",
    "hpke_open",
    "hpke_seal",
    "serialize_device_keys",
    "root_signing_key_id",
    "sign_http_request",
    "sign_message",
    "sign_service_challenge",
    "task_aad",
    "unwrap_task_key",
    "unwrap_task_key_for_workspace",
    "unwrap_workspace_key",
    "verify_http_request",
    "verify_allocation_proof",
    "verify_key_manifest",
    "verify_message",
    "verify_worker_owner_certificate",
    "workspace_key_aad",
    "wrap_task_key",
    "wrap_task_key_for_workspace",
    "wrap_workspace_key",
    "worker_certificate_digest",
]

__version__ = "0.1.0"
