#!/bin/bash

set -Eeuo pipefail

readonly CONFIG_PATH="/etc/nginx/conf.d/vgen-releases.conf"
readonly RELEASE_ROOT="/var/www/vgen-releases"

ACTION="${1:-}"
[[ -n "${ACTION}" ]] && shift
DOMAIN=""
CONFIRM_DOMAIN=""

die() {
  printf '[vgen-release-site] ERROR: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Configure the credential-free VGen download hostname on an existing Nginx host.

  sudo ./setup-release-site.sh install --domain downloads.example.com
  sudo ./setup-release-site.sh status --domain downloads.example.com

The TLS certificate must already exist under /etc/letsencrypt/live/<domain>/.
This script never changes DNS, Certbot, Gateway data, OSS, or firewall rules.
EOF
}

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --domain)
      [[ "$#" -ge 2 ]] || die "--domain requires a value"
      DOMAIN="$2"
      shift 2
      ;;
    --confirm-domain)
      [[ "$#" -ge 2 ]] || die "--confirm-domain requires a value"
      CONFIRM_DOMAIN="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) die "unknown argument: $1" ;;
  esac
done

[[ "${ACTION}" == "install" || "${ACTION}" == "status" ]] || {
  usage >&2
  exit 2
}
[[ "${EUID}" -eq 0 ]] || die "run this command as root"
[[ "${DOMAIN}" =~ ^[a-z0-9]([a-z0-9.-]{0,251}[a-z0-9])?$ ]] || \
  die "--domain must be a lowercase DNS hostname"
[[ -f "/etc/letsencrypt/live/${DOMAIN}/fullchain.pem" ]] || \
  die "TLS fullchain does not exist for ${DOMAIN}"
[[ -f "/etc/letsencrypt/live/${DOMAIN}/privkey.pem" ]] || \
  die "TLS private key does not exist for ${DOMAIN}"

if [[ "${ACTION}" == "status" ]]; then
  [[ -f "${CONFIG_PATH}" && ! -L "${CONFIG_PATH}" ]] || die "release Nginx config is absent"
  grep -Fq "server_name ${DOMAIN};" "${CONFIG_PATH}" || die "release config belongs to another domain"
  nginx -t
  curl --fail --silent --show-error "https://${DOMAIN}/releases/channels/stable.json"
  printf '\n[vgen-release-site] download site is healthy: https://%s/releases/\n' "${DOMAIN}"
  exit 0
fi

if [[ -z "${CONFIRM_DOMAIN}" ]]; then
  [[ -r /dev/tty && -w /dev/tty ]] || \
    die "non-interactive install requires --confirm-domain ${DOMAIN}"
  printf 'Please re-enter the download domain to confirm [%s]: ' "${DOMAIN}" >/dev/tty
  IFS= read -r CONFIRM_DOMAIN </dev/tty || die "domain confirmation was cancelled"
fi
[[ "${CONFIRM_DOMAIN}" == "${DOMAIN}" ]] || die "domain confirmation did not match"

install -d -o root -g root -m 0755 "${RELEASE_ROOT}" "${RELEASE_ROOT}/channels"
temporary="$(mktemp /etc/nginx/conf.d/.vgen-releases.XXXXXX.conf)"
backup=""
cleanup() { rm -f -- "${temporary}"; }
trap cleanup EXIT

cat >"${temporary}" <<EOF
# Generated by VGen for the credential-free download hostname.
server {
  listen 80;
  server_name ${DOMAIN};
  location /.well-known/acme-challenge/ { root /var/www/certbot; }
  location / { return 301 https://\$host\$request_uri; }
}
server {
  listen 443 ssl http2;
  server_name ${DOMAIN};
  ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header Referrer-Policy "no-referrer" always;
  location = /releases/channels/stable.json {
    alias ${RELEASE_ROOT}/channels/stable.json;
    default_type application/json;
    add_header Cache-Control "public, max-age=0, must-revalidate" always;
  }
  location = /releases/install-macos.sh {
    alias ${RELEASE_ROOT}/install-macos.sh;
    default_type text/x-shellscript;
    add_header Cache-Control "public, max-age=0, must-revalidate" always;
    add_header Content-Disposition 'attachment; filename="install-macos.sh"' always;
  }
  location = /releases/install-windows-worker.ps1 {
    alias ${RELEASE_ROOT}/install-windows-worker.ps1;
    default_type text/plain;
    add_header Cache-Control "public, max-age=0, must-revalidate" always;
    add_header Content-Disposition 'attachment; filename="install-windows-worker.ps1"' always;
  }
  location ~ "^/releases/(?<vgen_release_version>[0-9]+(?:\.[0-9]+){2})/(?<vgen_release_file>[A-Za-z0-9][A-Za-z0-9._+-]{0,191})\$" {
    alias ${RELEASE_ROOT}/\$vgen_release_version/\$vgen_release_file;
    add_header Cache-Control "public, max-age=31536000, immutable" always;
  }
  location / { return 404; }
}
EOF
chmod 0600 "${temporary}"

if [[ -e "${CONFIG_PATH}" ]]; then
  [[ -f "${CONFIG_PATH}" && ! -L "${CONFIG_PATH}" ]] || die "existing release config is unsafe"
  backup="${CONFIG_PATH}.backup.$(date -u +%Y%m%dT%H%M%SZ)"
  cp -a -- "${CONFIG_PATH}" "${backup}"
fi
install -o root -g root -m 0644 "${temporary}" "${CONFIG_PATH}"
if ! nginx -t || ! systemctl reload nginx; then
  if [[ -n "${backup}" ]]; then
    install -o root -g root -m 0644 "${backup}" "${CONFIG_PATH}"
  else
    rm -f -- "${CONFIG_PATH}"
  fi
  nginx -t && systemctl reload nginx || true
  die "Nginx validation failed; the previous release-site config was restored"
fi
printf '[vgen-release-site] configured https://%s/releases/\n' "${DOMAIN}"
