"""Build the auditable, source-free Gateway installation bundle."""

from __future__ import annotations

import argparse
import hashlib
import io
import re
import shutil
import tarfile
import tempfile
import tomllib
import zipfile
from email.parser import Parser
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[1]


def _project_version(repository: Path) -> str:
    with (repository / "pyproject.toml").open("rb") as handle:
        value = tomllib.load(handle).get("project", {}).get("version")
    if not isinstance(value, str) or re.fullmatch(
        r"(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)\.(?:0|[1-9][0-9]*)", value
    ) is None:
        raise ValueError("project.version must be an unprefixed MAJOR.MINOR.PATCH release")
    return value


VERSION = _project_version(REPOSITORY)
WHEEL_NAME = f"vgen-{VERSION}-py3-none-any.whl"
BUNDLE_NAME = f"vgen-gateway-{VERSION}"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _validate_wheel(path: Path, *, version: str) -> None:
    expected_name = f"vgen-{version}-py3-none-any.whl"
    if path.name != expected_name:
        raise ValueError(f"wheel must be named {expected_name}")
    if path.is_symlink():
        raise ValueError("wheel must not be a symbolic link")
    try:
        with zipfile.ZipFile(path) as archive:
            names = archive.namelist()
            if len(names) != len(set(names)):
                raise ValueError("wheel contains duplicate paths")
            if any(
                name.startswith(("/", "\\"))
                or ".." in Path(name.replace("\\", "/")).parts
                for name in names
            ):
                raise ValueError("wheel contains an unsafe path")
            metadata_names = [name for name in names if name.endswith(".dist-info/METADATA")]
            wheel_names = [name for name in names if name.endswith(".dist-info/WHEEL")]
            if len(metadata_names) != 1 or len(wheel_names) != 1:
                raise ValueError("wheel metadata is incomplete")
            package_metadata = Parser().parsestr(
                archive.read(metadata_names[0]).decode("utf-8")
            )
            wheel_metadata = archive.read(wheel_names[0]).decode("utf-8")
    except (OSError, UnicodeDecodeError, zipfile.BadZipFile, KeyError) as exc:
        raise ValueError("wheel is not a readable Python wheel") from exc
    if package_metadata.get("Name", "").casefold() != "vgen":
        raise ValueError("wheel distribution name must be vgen")
    if package_metadata.get("Version") != version:
        raise ValueError(f"wheel metadata version must be {version}")
    if "Tag: py3-none-any" not in wheel_metadata.splitlines():
        raise ValueError("wheel must contain the py3-none-any tag")


def _parser() -> argparse.ArgumentParser:
    repository = REPOSITORY
    parser = argparse.ArgumentParser(
        description="Build a VGen Gateway bundle that does not require the source tree."
    )
    parser.add_argument("--wheel", type=Path, default=repository / "dist" / WHEEL_NAME)
    parser.add_argument(
        "--output",
        type=Path,
        default=repository / "dist" / f"{BUNDLE_NAME}.tar.gz",
    )
    return parser


_GATEWAY_GUIDE_START = "<!-- VGEN_GATEWAY_INSTALL_BEGIN -->"
_GATEWAY_GUIDE_END = "<!-- VGEN_GATEWAY_INSTALL_END -->"


def _install_text(repository: Path) -> str:
    """Extract the offline Gateway card from the single user-guide source."""

    guide = (repository / "docs" / "user-guide.md").read_text(encoding="utf-8")
    if guide.count(_GATEWAY_GUIDE_START) != 1 or guide.count(_GATEWAY_GUIDE_END) != 1:
        raise ValueError("user guide must contain exactly one Gateway install section")
    section = guide.split(_GATEWAY_GUIDE_START, 1)[1].split(_GATEWAY_GUIDE_END, 1)[0].strip()
    if not section.startswith("## 3. ECS Gateway"):
        raise ValueError("Gateway install section has an unexpected heading")
    return (
        "VGen Gateway offline install card\n"
        "Generated from docs/user-guide.md; do not edit this file separately.\n\n"
        f"{section}\n"
    )


def build_bundle(*, repository: Path, wheel: Path, output: Path) -> Path:
    version = _project_version(repository)
    wheel_name = f"vgen-{version}-py3-none-any.whl"
    bundle_name = f"vgen-gateway-{version}"
    installer = repository / "examples" / "ecs" / "setup-gateway.sh"
    service = repository / "examples" / "ecs" / "vgen-gateway.service"
    for source in (wheel, installer, service):
        if not source.is_file():
            raise FileNotFoundError(source)

    _validate_wheel(wheel, version=version)

    output = output.expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="vgen-gateway-bundle-") as temporary:
        bundle_root = Path(temporary) / bundle_name
        bundle_root.mkdir(mode=0o700)
        destinations = {
            wheel: bundle_root / wheel_name,
            installer: bundle_root / "setup-gateway.sh",
            service: bundle_root / "vgen-gateway.service",
        }
        for source, destination in destinations.items():
            shutil.copyfile(source, destination)
            destination.chmod(0o755 if destination.name.endswith(".sh") else 0o644)

        install_file = bundle_root / "INSTALL.txt"
        install_file.write_text(_install_text(repository), encoding="utf-8")
        install_file.chmod(0o644)

        manifest_entries = []
        for path in sorted(bundle_root.iterdir(), key=lambda candidate: candidate.name):
            if path.name == "SHA256SUMS":
                continue
            manifest_entries.append(f"{_sha256(path)}  {path.name}")
        manifest = bundle_root / "SHA256SUMS"
        manifest.write_text("\n".join(manifest_entries) + "\n", encoding="utf-8")
        manifest.chmod(0o644)

        # Use stable metadata so rebuilding the same reviewed inputs produces
        # the same archive. gzip mtime is fixed through tarfile's file object.
        compressed = io.BytesIO()
        import gzip

        with gzip.GzipFile(filename="", mode="wb", fileobj=compressed, mtime=0) as gzip_stream:
            with tarfile.open(fileobj=gzip_stream, mode="w") as archive:
                for path in sorted(bundle_root.iterdir(), key=lambda candidate: candidate.name):
                    info = archive.gettarinfo(path, arcname=f"{bundle_name}/{path.name}")
                    info.uid = 0
                    info.gid = 0
                    info.uname = "root"
                    info.gname = "root"
                    info.mtime = 0
                    with path.open("rb") as handle:
                        archive.addfile(info, handle)
        output.write_bytes(compressed.getvalue())
        output.chmod(0o644)
    return output


def main() -> int:
    arguments = _parser().parse_args()
    repository = REPOSITORY
    destination = build_bundle(
        repository=repository,
        wheel=arguments.wheel.expanduser().resolve(),
        output=arguments.output,
    )
    print(f"bundle={destination}")
    print(f"sha256={_sha256(destination)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
