"""Stable, executor-neutral wire contracts shared by all VGen runtimes."""

from .errors import (
    ERROR_REGISTRY,
    ErrorCode,
    ErrorOrigin,
    ErrorSpec,
    Responsibility,
    RetryAction,
    VGenError,
    error_envelope,
    get_error_spec,
)
from .ids import ID_PREFIXES, new_id, validate_id
from .models import (
    ATTEMPT_TRANSITIONS,
    TASK_TRANSITIONS,
    ArtifactRef,
    AttemptState,
    ExecutionArtifact,
    ExecutionRequest,
    ExecutionResult,
    ExecutorDescriptor,
    TaskState,
    UsageReport,
    can_transition_attempt,
    can_transition_task,
    require_attempt_transition,
    require_task_transition,
)

__all__ = [
    "ATTEMPT_TRANSITIONS",
    "ERROR_REGISTRY",
    "ID_PREFIXES",
    "TASK_TRANSITIONS",
    "ArtifactRef",
    "AttemptState",
    "ErrorCode",
    "ErrorOrigin",
    "ErrorSpec",
    "ExecutionArtifact",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutorDescriptor",
    "Responsibility",
    "RetryAction",
    "TaskState",
    "UsageReport",
    "VGenError",
    "can_transition_attempt",
    "can_transition_task",
    "error_envelope",
    "get_error_spec",
    "new_id",
    "require_attempt_transition",
    "require_task_transition",
    "validate_id",
]
